apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: "2024-04-19T00:42:19Z"
  generation: 4
  labels:
    io.kompose.service: microservicios-mysql8
  name: microservicios-mysql8
  namespace: ventas2
  resourceVersion: "5071113"
  uid: 373b8865-89d2-43e7-b346-ba75a32e56be
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: microservicios-mysql8
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
        kubectl.kubernetes.io/restartedAt: "2024-04-20T00:08:05Z"
      creationTimestamp: null
      labels:
        io.kompose.network/springcloud: "true"
        io.kompose.service: microservicios-mysql8
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: db_springboot_cloud
        - name: MYSQL_ROOT_PASSWORD
          value: sasa
        - name: TZ
          value: America/Santiago
        image: mysql:5.7.43
        imagePullPolicy: IfNotPresent
        name: microservicios-mysql8
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqldata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: pvc-mysql
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-19T12:36:40Z"
    lastUpdateTime: "2024-04-20T00:08:38Z"
    message: ReplicaSet "microservicios-mysql8-769f56f98c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-04T18:56:24Z"
    lastUpdateTime: "2024-05-04T18:56:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
