apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-04-19T12:29:49Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-mysql
  resourceVersion: "4761160"
  uid: a88da864-670f-4c43-816d-04578fdbd1b5
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-mysql
    namespace: ventas2
    resourceVersion: "4761158"
    uid: 1f9bd671-1c54-4c16-a5e5-9c6f2997e5e5
  nfs:
    path: /opt/sfw
    server: 192.168.2.222
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
