apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: "2024-04-20T02:38:48Z"
  generation: 3
  labels:
    io.kompose.service: servicio-productos
  name: servicio-productos
  namespace: ventas2
  resourceVersion: "5071083"
  uid: ed3b00b0-8f5b-4b42-8e92-1070b6ba5ae8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: servicio-productos
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/springcloud: "true"
        io.kompose.service: servicio-productos
    spec:
      containers:
      - image: 96552333aa/servicio-productos:v6
        imagePullPolicy: IfNotPresent
        name: servicio-productos
        ports:
        - containerPort: 8001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-20T02:38:48Z"
    lastUpdateTime: "2024-04-20T16:49:04Z"
    message: ReplicaSet "servicio-productos-6bcddb7667" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-04T18:56:23Z"
    lastUpdateTime: "2024-05-04T18:56:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
