apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: "2024-04-20T17:28:16Z"
  generation: 1
  labels:
    io.kompose.service: servicio-ng-front-vtas
  name: servicio-ng-front-vtas
  namespace: ventas2
  resourceVersion: "5071028"
  uid: 65351b42-89f2-479c-be9f-42c068834f36
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: servicio-ng-front-vtas
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/springcloud: "true"
        io.kompose.service: servicio-ng-front-vtas
    spec:
      containers:
      - image: 96552333aa/servicio-ng-front-vtas:v2
        imagePullPolicy: IfNotPresent
        name: servicio-ng-front-vtas
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-20T17:28:16Z"
    lastUpdateTime: "2024-04-20T17:28:21Z"
    message: ReplicaSet "servicio-ng-front-vtas-58b4468cf9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-04T18:56:22Z"
    lastUpdateTime: "2024-05-04T18:56:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
