apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-02-14T13:45:28Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-mysql
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-mysql
    namespace: ventas2
  nfs:
    path: /opt/sfw
    server: 192.168.2.222
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
