apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: servicio-ng-front-vtas
  name: servicio-ng-front-vtas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: servicio-ng-front-vtas
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/springcloud: "true"
        io.kompose.service: servicio-ng-front-vtas
    spec:
      containers:
      - image: 96552333aa/servicio-ng-front-vtas:v2
        imagePullPolicy: ""
        name: servicio-ng-front-vtas
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
